defaults: &defaults
  webpuzzle_front_auth_end: '/auth/github/end/'
  github_api_v3: https://api.github.com

development: &development
  <<: *defaults
  webpuzzle_front: http://localhost:3030/webpuzzle/web/index.html#

development_ig2i:
  <<: *development

test:
  <<: *defaults
  webpuzzle_front: http://localhost:9000/#!

production:
  <<: *defaults
  webpuzzle_front: https://webpuzzle.herokuapp.com/#
