defaults: &defaults
  webpuzzle_front: http://localhost:9000/#!
  webpuzzle_front_auth_end: '/auth/github/end/'
  github_api_v3: https://api.github.com

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  webpuzzle_front: http://webpuzzlefront.herokuapp.com